### ISSUE TITLE
Authentication Part 1 - VVSG Roles & Flows

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite-roadmap#13]
## Team

Product Definition and Scoping: @benadida 
Design: @beausmith 
VVSG: @mattroe 
Eng DRI: @arsalansufi

### What is the feature or problem to solve?
Role-based access control based on VVSG2 requirements.

### What does a successful outcome of this project look like?
The entire VxSuite of products has a secure authentication system with a clear and understandable set of user roles that meet the needs of our customers in Mississippi, and are flexible to for-seeable future customer needs. This set of user roles, and the overall authentication system also must meet the various certification requirements for VVSG 2.0. 

### Timeline
 
User Flows - m14 Code Freeze 

## Supporting Documentation 

- [Product Spec](https://docs.google.com/document/d/1jUCM7nnXLj_6dB8ErmWzTPztzpx0eOP1rYpx5Zm_slI/edit?usp=sharing)
- [User Screens and Flows Spec](https://docs.google.com/document/d/1jBoQqIE7IEr3G_zGfAkl0gDD2kammjIDzpOf7K7StsI/edit?usp=sharing)
- [Previous doc](https://docs.google.com/document/d/1p7FrnqWdwe11s5cZfOK2DjPI8Dou2LU-UjW5j-VQ5ak/edit?usp=sharing)

## Tasks

**VxAdmin UI scaffolding (0.5 eng weeks)**

- [x] https://github.com/votingworks/vxsuite/issues/1911
- [x] https://github.com/votingworks/vxsuite/issues/1923

**VxAdmin super admin base screens (1.5 eng weeks)**

- [x] https://github.com/votingworks/vxsuite/issues/1912
- [x] https://github.com/votingworks/vxsuite/issues/1913
- [x] https://github.com/votingworks/vxsuite/issues/1914
- [x] https://github.com/votingworks/vxsuite/issues/1927
- [x] https://github.com/votingworks/vxsuite/issues/1977
- [x] https://github.com/votingworks/vxsuite/issues/1978

**VxAdmin super admin screen tweaks (1.5 eng weeks)**

- [ ] (m14 puntable) https://github.com/votingworks/vxsuite/issues/1916
- [ ] (m14 puntable) https://github.com/votingworks/vxsuite/issues/1917
- [x] https://github.com/votingworks/vxsuite/issues/1979
- [x] https://github.com/votingworks/vxsuite/issues/1974
- [x] https://github.com/votingworks/vxsuite/issues/1975

**Other screens (1.5 eng weeks)**

- [x] https://github.com/votingworks/vxsuite/issues/1910
- [x] https://github.com/votingworks/vxsuite/issues/1980
- [x] https://github.com/votingworks/vxsuite/issues/1739

**Card programming (2 eng weeks)**

- [x] https://github.com/votingworks/vxsuite/issues/1918
- [x] https://github.com/votingworks/vxsuite/issues/1919
- [x] https://github.com/votingworks/vxsuite/issues/1920
- [x] https://github.com/votingworks/vxsuite/issues/1921

**Unique PIN generation (2 eng weeks)**

- [ ] (m14 puntable) https://github.com/votingworks/vxsuite/issues/1924
- [ ] (m14 puntable) https://github.com/votingworks/vxsuite/issues/1926
- [ ] (m14 puntable) https://github.com/votingworks/vxsuite/issues/1986

**Miscellaneous (1.5 eng weeks)**

- [x] https://github.com/votingworks/vxsuite/issues/1928
- [x] https://github.com/votingworks/vxsuite/issues/1976
- [x] https://github.com/votingworks/vxsuite/issues/2181
- [x] https://github.com/votingworks/vxsuite/issues/2171
- [ ] (m14 puntable) https://github.com/votingworks/vxsuite/issues/1991
- [ ] (m14 puntable) https://github.com/votingworks/vxsuite/issues/2048
- [ ] (m14 puntable) https://github.com/votingworks/vxsuite/issues/2085

**Issues identified during testing**

- [x] https://github.com/votingworks/vxsuite/issues/2170
- [x] https://github.com/votingworks/vxsuite/issues/2200
- [x] https://github.com/votingworks/vxsuite/issues/2203

**Summary**

10.5 eng weeks + 1.5 eng weeks buffer for unknowns = ~12 eng weeks

Arsalan: 8 eng weeks (through first week of August)
Drew: 3 eng weeks (through first week of August)
Jonah: 1 eng week (natural overlap given Jonah's auth refactor work)

_6/13 - 6/17_

- VxAdmin UI scaffolding
- VxAdmin super admin base screens

_6/20 - 6/24_

- VxAdmin super admin base screens
- VxAdmin super admin screen tweaks
- Other screens

_6/27 - 7/1_

- VxAdmin super admin screen tweaks
- Other screens
- Card programming

_7/4 - 7/8_

- VxAdmin super admin screen tweaks
- Other screens
- Card programming

_7/11 - 7/15_

- Card programming

_7/18 - 7/22_

- Card programming
- Miscellaneous

_7/25 - 7/29_

- Straggler tickets across categories

**Comment by mattroe** [comment]
Roles proposal: https://docs.google.com/document/d/1jUCM7nnXLj_6dB8ErmWzTPztzpx0eOP1rYpx5Zm_slI/edit

**Comment by carolinemodic** [comment]
Related VVSG Requirements
10.2.3-A: The voting system must require administrator-level authorization to access the directory or storage location of CVRs, ballot images, and ballot selections. Cast vote records, ballot images, and ballot selections should be subject to special restrictions on access. Permissions to access these storage locations are limited only to those users who need to access the location. This may be especially essential during voting to protect ballot secrecy and avoid any exposure of results until polls are closed.
11.2.1-A: The voting system must allow only authorized users to access the voting system.
11.2.1-B: The voting system must allow only an administrator to create or modify the list of authorized users.
11.2.1-C: The voting system access control mechanisms must distinguish at least the following voting stages from Table 11-1.
11.2.1-D: The voting system must allow only an administrator to configure the permissions and functionality for each identity, group or role, or process to include account and group or role creation, modification, disablement, and deletion.
11.2.1-E: The voting system must allow only an administrator to create or modify permissions assigned to specific groups or roles.
11.2.1-F: The voting system must allow only an administrator to create or assign the groups or roles.
11.2.2-A: Voting systems that implement role-based access control must support the recommendations for Core Role Based Access Control (RBAC) in the ANSI INCITS 359-2004 American National Standard for Information Technology – Role Based Access Control [ANSI04] document.
11.2.2-B: At minimum, voting systems that implement RBAC must define groups or roles with the role descriptions within Table 11-2.
11.2.2-C: At minimum, the voting system must use the groups or roles from Table 11-2 – Minimum voting system groups or roles for RBAC and the voting stages from Table 11-1 – Voting stage descriptions, to assign the minimum permissions in Table 11-3.
11.2.2-D: The voting system must be capable of applying assigned groups or roles and permissions to authorized users.
11.3.1-A: The voting system must use access control mechanisms to permit authorized access or prevent unauthorized access to the voting system.
11.3.1-B: At a minimum, the voting system must be capable of using multi-factor authentication to verify a user has authorized access to perform critical operations, including: 1/ runtime software updates to the certified voting system 2/ aggregation and tabulation 3/ enabling network functions 4/ changing device states, including opening and closing the polls 5/ deleting or modifying the CVRs and ballot images 6/ modifying authentication mechanisms
11.3.1-C: The voting system must authenticate the administrator with a multi-factor authentication mechanism.
11.3.2-A: If the voting system uses a username and password authentication method, the voting system must allow only the administrator to enforce password strength, histories, and expiration.
11.3.2-B: The voting system must, at minimum, meet the password complexity requirements within the latest version of NIST SP 800-63B Digital Identity Guidelines standards.
11.3.2-C: The voting system must store authentication data in a way that ensures confidentiality and integrity are preserved.
11.3.2-D: The voting system must compare all passwords against a manufacturer-specified list of well-known weak passwords and disallow the use of these weak passwords.
11.3.2-E: The voting system must ensure that the username is not used in the password.
11.4-A: By default, the voting system must implement the principle of least privilege including denying access to functions and data unless explicitly permitted.
11.4-B: Voting system documentation must include suggested practices for dispersing critical operations across multiple groups or roles.
11.5-A: The voting system must enable an administrator the ability to do the following: 1/ set the maximum time limit for a user’s session 2/ set the maximum time limit for user inactivity
11.5-B: The voting system must require reauthentication of an authorized user after the administrator-specified time limit for the user’s session or for user inactivity.
11.5-C: The voting system must lockout roles or individuals after an administrator-specified number of consecutive failed authentications attempts.
11.5-D: The voting system must allow only an administrator to define the lockout duration.
13.1.1-A: The voting system must allow only authenticated system administrators to access and modify voting device configuration files.Voting system configuration files can include operating system and voting system application configuration files. These files can have a large impact on how the voting system functions and what election logic is being used. Therefore, accidental or malicious modification can have a large impact on the system and access to these files should be restricted to authorized individuals. Applies to: Vote-capture and tabulation system
13.1.1-B: The EMS must uniquely authenticate individuals associated with the role of system administrator before allowing them to access and modify EMS configuration files. EMS configuration files can include operating system and voting system application configuration files. These files can have a large impact on how an EMS tabulates and reports election results. Therefore, accidental or malicious modification can have a large impact on the system and access to these files should be restricted to authorized individuals. Applies to: EMS workstation
