### ISSUE TITLE
Enhanced System Integrity v1

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite-roadmap#3]
## Team

Eng DRI: @umbernhard 
Product Definition and Security Advisor: @benadida 

Product Spec:
https://docs.google.com/document/d/1zVfXbeoYbJt0Dz1-Kn5yhcoRRco0V8kusjIsJQZvhM4/edit#

### What is the feature or problem to solve?
dm-verity, a unified kernel, kernel command line, and bootloader, and secure boot signing functionality backed by one time passwords. Proves our system is secure and has not been modified. A possible security & sales differentiator over competitive systems as we believe VotingWorks is uniquely secure from attacks with ESI. Includes functionality required for certification.

### What does a successful outcome of this project look like?
We have deployed for m14, a fully tested suite of ESI features that have been tested on all of our applications, on all of our hardware, thoroughly and introduce no regressions or other bugs. These features need to not only implement the desired security measures, and do so without introducing new bugs, but needs to come with a defined process for how we update machines in the field to use ESI that were not shipped with ESI for m13b and how we provision and install new machines with ESI.

ESI will not be complete on VxScan. VxScan will still have some of the ESI v1 features but not the same level of treatment of the other machines (under the assumption we move to Debian).

## Tasks & Timeline

- [x] https://github.com/votingworks/vxsuite/issues/1758
- [x] https://github.com/votingworks/vxsuite/issues/1502

### June 24: working productionized VxSuite
- [x] https://github.com/votingworks/vxsuite/issues/1857
- [x] Fixing all issues with partitioning scheme & read-only partitions.
- [x] Stop setting hostname with machine ID
- [x] Fix how we set timezone to be durable
- [x] Prepare a bunch of USB mount points as usb-drive-1, etc...
- [x] Fix printer configuration on read-only fs
- [x] https://github.com/votingworks/vxsuite/issues/1858
- [x] write up the key management spec for PK
- [x] write up documentation of various secure boot methods to record our decision

### *July 1*: vx-iso setting up secure boot on m13b & fresh machines
- [x] https://github.com/votingworks/vxsuite/issues/1859
- [x] decide on MOK vs. not MOK and process with Microsoft.
- [x] https://github.com/votingworks/vxsuite/issues/1860
- [x] Defined software update in the field flow

### *July 8th*
- [ ] BIOS settings process for setup mode & docs
- [x] sealing secrets inside TPM

### *July 15*: Integration
- [x] update kiosk-browser and verification stack to ECDSA / tpm signatures.
- [ ] test installation on various hardware
- [ ] full documentation for installation on all hardware
- [ ] code-signing key generation scripts for testing

### *July 22*: Testing
- [ ] stress testing at bakery
- [ ] code-signing key process finalized

### *Aug 5*: Application-level features
- [ ] Application-level signing keys sealed in TPM
- [ ] Code-signing keys generated and distributed
- [ ] Live Check

### *Aug 5*: Code Freeze

Not in scope for m14:
* Durable Evidence

**Comment by mattroe** [comment]
14.3.1-A: The voting system must cryptographically verify firmware and software integrity before the operating system is loaded into memory. This requirement does not mandate hardware support for cryptographic verification. This requirement could be met by trusted boot, but other software-based solutions exist. This includes a software bootloader cryptographically verifying the OS prior to execution. Verifying the bootloader itself is excluded from this requirement, but not prohibited. Applies to: Vote-capture and tabulation device, EMS
14.3.1-B: If the voting system fails boot validation, the voting system must not boot and provide an onscreen alert. System users need to be notified when the voting system is either corrupted or has been maliciously modified. Boot validation prevents unauthorized operating systems and software from being installed or run on a system. Applies to: Vote-capture and tabulation device, EMS
14.3.1-C: If the voting system does not pass boot validation, it must present an on-screen alert and provide any other necessary information to understand the failure. Failure of boot validation needs to be provided to users so these errors can be further analyzed when needed. If the voting system is capable of pre-boot logging, failure information could be stored in a log for future analysis. Applies to: Vote-capture and tabulation, EMS
14.3.2-A: The voting system must only allow digitally signed software and firmware to be installed. Signed software and firmware ensures that it is not modified before installation, and that it is being distributed by the proper entity.
14.3.2-C: The voting system must only run applications that have been verified against an allowlist. This requirement helps ensure only authorized applications run on the voting system. Applies to: Vote-capture device
14.3.2-D: The voting system must protect the integrity and authenticity of the allowlist configuration files. If the allowlist is improperly modified, the software allowlisting mitigation can be defeated. The most common way of providing allowlist configuration file protection could be a digital signature.
14.4-A: The voting system must authenticate administrators before an operating system update is performed. Administrators are required to be authenticated before they can update the voting system, regardless of whether the updated done by a networked method or performed using physical media.
14.4-B: The voting system must authenticate administrators before a software update to the voting system application and related software. Administrators are required to be authenticated before they can update the voting system, whether the update is applied by a network method or physical media.
14.4-C: The voting system must authenticate administrators before a firmware or driver update. Administrators are required to be authenticated before they can update the voting system, regardless if network enabled update is performed or via physical media.
15.3-A: COTS workstations providing EMS functionality must deploy mechanisms to protect against malware. NIST SP 800-83 Revision 1 Guide to Malware Incident Prevention and Handling for Desktops and Laptops [NIST13a] might be useful as supplemental guidance for protecting against malware. Malware protection mechanisms are not required for voter-facing scanners and electronic BMDs. Alternatively, voter-facing scanners and electronic BMDs are required to use protection mechanisms, such as digital signatures and allowlists. This requirement is focused on EMS COTS workstations and does not include peripherals devices (e.g., printers).
15.3-B: The malware protection mechanisms for COTS devices providing EMS functionality must be updatable. Malware protection mechanisms typically use software signatures to identify malware. As new malware signatures are received, the malware protection mechanism needs to be updated with the new signatures to ensure it is identifying all known malware. Applies to: EMS Workstations, vote-capture and tabulation devices.
15.3-C: The voting system documentation must include the process and procedures for updating malware protection mechanisms. Providing documentation of the procedures to configure the malware protection mechanisms assists with ensuring the malware protection mechanisms are properly updated to meet 15.3.-B- Updatable malware protection mechanisms.
15.3-D: COTS workstations and servers providing EMS functionality must immediately notify an election official when malware is detected. Malware on an EMS device can disrupt the integrity of the data on the EMS device. Once malware is detected, immediate notification of malware detection allows election officials to promptly take the proper action to avoid data integrity issues. This requirement is focused on EMS COTS workstations and does not include peripheral devices (e.g., printers).
15.3-E: The voting system must log instances of detecting malware.
15.3-F: COTS workstations and servers providing EMS functionality must provide a notification upon the removal or remediation of malware. Once malware it is identified on a device, operations can cease until the malware is remediated. This notification allows administrators and officials to know when it is safe to resume normal operations. This requirement is focused on EMS COTS workstations and does not include peripherals devices (e.g., printers)
15.3-G: Once malware it is identified on a device, operations can cease until the malware is remediated. This notification allows administrators and officials to know when it is safe to resume normal operations. This requirement is focused on EMS COTS workstations and does not include peripherals devices (e.g., printers) Remediation that requires the reimaging or reinstallation of the OS, may need to be logged external to the voting system. Prior to reimaging, the malware detection logs could be downloaded and stored on another system to capture the time stamp of the malware event and preserve the malware event log for further analysis.
TA151E-1: The voting system MUST log identifying information of EITHER the group accessing
configuration files or identifying information of the role of users accessing configuration files.
TA151E-1-1: The logged identifying information MAY include the username or the name
of the user.
TA151E-1-2: The voting system log MUST contain the time of access for a configuration
file.
TA153A-1: IF a COTS workstation provides EMS functionality, THEN the voting system MUST utilize application allow listing or MUST use digital signatures on the COTS EMS devices in order to protect against malware.
TA153A-2: IF malware protection is an included feature of the system, THEN the voting system MUST launch applications providing malware protection before the voting application is loaded.
TA153B-1: IF new malware signatures are received for COTS devices providing EMS
functionality, THEN malware protection mechanisms MUST be capable of being updated with the new signatures.
TA153D-1: COTS workstations providing EMS functionality MUST immediately notify a user when malware is detected on COTS EMS devices.
TA153D-1-1: COTS workstations providing EMS functionality MUST make malware
detection notifications on-screen.
TA153E-1: IF malware is detected THEN the voting system MUST log every instance of
detection.
