### ISSUE TITLE
Design System & UI Library Improvements

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite-roadmap#44]
## Team
@beausmith - Owner

### What is the feature or problem to solve?
The eng team uses a [shared components library](https://github.com/votingworks/vxsuite/tree/main/libs/ui) to build user interfaces and screens throughout the product. This makes it easy for an engineer to quickly put together a UI for a feature, without needing a lot of design expertise, that will have a simple, clear design consistent with the rest of the applications. Historically all of the applications used to have separate codebases and there was no shared UI library, we have slowly moved things in there over time but there are still gaps where some components exist in both the shared and individual app codebases. Now that the eng team is larger and working on more things in parallel it is also worth investing some time improving the library as a whole: Improving the layout components for easier use, adding best practices around things like layout, copy, color, etc. On [4/25 in the prod/eng weekly meeting](https://docs.google.com/document/d/1pszW9efkfQOwlzUFMNnaU8bC7MfLHPz6zSM9vcPKngg/edit#bookmark=id.htlf6e3ovsej) we brainstormed a list of potential improvements. 

### What does a successful outcome of this project look like?
We have improved the components in the libs/ui library, and added more supporting documentation to make it clear and easy for engineers to take the lego blocks of the design system and put them together into usable, consistent UIs. Success is measured by the engineers feeling like the design system is easier to use, Beau needing to spend less time providing design guidance on specific details (ex: capitalization best practices), and our resulting UIs becoming more consistent. 

## Supporting Documentation 
 
[Prod/Eng Meeting Brainstorm
](https://docs.google.com/document/d/1pszW9efkfQOwlzUFMNnaU8bC7MfLHPz6zSM9vcPKngg/edit#bookmark=id.htlf6e3ovsej)

## Tasks

- [x] https://github.com/votingworks/vxsuite/issues/1757
- [x] https://github.com/votingworks/vxsuite/issues/1776
- [x] https://github.com/votingworks/vxsuite/issues/1778
- [x] Refactor away `MainChild`
- [x] Refactor `Screen` component
- [x] https://github.com/votingworks/vxsuite/issues/1779
- [x] Draft a Style Guide "readme" in `vxsuite` to include
    - [x] Writing Style
    - [x] Prose - What is Prose? How to use it.

**Comment by beausmith** [comment]
With the above two docs-related PRs, this task is complete.
