### ISSUE TITLE
m14 Hardware Improvements

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite-roadmap#56]
## Team
* Product: @mattroe 
* Hardware Production: @adghayes 

### What is the feature or problem to solve?
Determine what mitigations / solutions we want to include in m14 to address the hardware problems seen during m13.

The primary issues seen during m13 were:
- higher incident rates of paper jams & zombie ballots
- paper jams on ejections

### What does a successful outcome of this project look like?
We are confident in mitigations / solutions from internal testing and see a lower rate of hardware incidents during m14. 

### Timeline
A final m14 hardware change plan must be in place and thoroughly tested by the m14 code freeze date (8/8).

## Supporting Documentation 
- [m13 hardware issue summary](https://docs.google.com/document/d/1zRvIydmmjevUB3ismWHjFuOasC3zN6CtDipA6nCNQ_Y/edit#)
- [m13 retro](https://docs.google.com/document/d/1FRpWlnEjVeVBMwqAcJOdd4emV1k9MoonNJiNxHwt4f4/edit)
- [double scan debugging](https://docs.google.com/document/d/1Ow_KFargJHgo_Nn_iWiLn5NR9BbIEpZlm6_ffyjbLi8/edit#)

## What is a test run?
1,200 ballots to exceed target ballot bag capacity of 1,000 ballots. Test runs will be documented in a spreadsheet with associated experiment, number of ballots scanned, and results summary.

## Tasks
By order of priority of testing:

*Brackets*
- [x] Test plastic bracket intervention to determine if we want to include in m14

*Paper Weight* 
- [x] votingworks/vxsuite#2005
- [x] Letter vs. legal test for both paper weights
- [x] Ballot bag capacity for both paper weights
- [x] Determine based on paper weight selection how to to print HMPB ballots
- [x] Determine based on paper weight selection how to to print BMD ballots

*Ballot Bag Modifications* (votingworks/vxsuite#2014)
- [x] New ballot bag sample with hardened front & built-in ramp
- [x] Test ramp samples: 1/ full length, same height 2/ current length, higher height 3/ full length, higher height 4/ current length, current height (no backstop)
- [x] Reproduce the issues discovered during #m13c - aka "the wall"
- [x] Ballot bag capacity & paper weight tests on full-full-length ramps on updated plustek

*Misc*
- [x] https://github.com/votingworks/vxsuite/issues/1938
