### ISSUE TITLE
VVSG CVRs

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite-roadmap#63]
## Tasks
- [ ] https://github.com/votingworks/vxsuite/issues/1333
- [ ] https://github.com/votingworks/vxsuite/issues/1334
- [ ] https://github.com/votingworks/vxsuite/issues/1335
- [ ] https://github.com/votingworks/vxsuite/issues/1336
- [ ] https://github.com/votingworks/vxsuite/issues/1337
- [ ] https://github.com/votingworks/vxsuite/issues/1338
- [ ] https://github.com/votingworks/vxsuite/issues/1339
- [ ] https://github.com/votingworks/vxsuite/issues/184
