### ISSUE TITLE
VxDev v1

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite-roadmap#8]
## Team

Eng DRI: @carolinemodic 

### What is the feature or problem to solve?
A development version of our hardware, meaning the real hardware, but with software that is in development mode, easily updatable to the latest version over the Internet.

It’s very difficult for non-Vx-engineers to use the latest features of the VotingWorks voting system. This makes for some unpleasant last minute surprises for folks who are not developing on the system, it reduces the amount of useful feedback we can get before actual releases, and it makes it difficult for non-engineers to do parts of their jobs closely tied to product features, e.g. writing documentation. We want it to be easy for a VotingWorks team member to try out the latest features.

### What does a successful outcome of this project look like?
We have a version of our voting machines that:

1. The customer facing team can use internally to test out recent changes, demo the system, take screenshots, and do other tasks they need to do on a daily basis with our product. 
2. The engineering team can use internally to get their hardware to a good base version for testing and iterating. 
3. Important customers, and members of an advisory board can use to test out recent changes and provide feedback to the VotingWorks team. 

### Timeline
 
Initial Alpha Version for testing by the eng team and @mattroe : Available by the week of 5/2 
Initial Beta Version for testing from internal customer-facing team members: Ship USB install weeks by mid-May. 
Version ready for customers to use: ??? 

## Supporting Documentation 
 
[Design Doc
](https://docs.google.com/document/d/1jm0jLKinBzdFm8Z0gfxcdHp4FxEjC3EbJ89kOZHBSVU/edit#heading=h.ji14ncc4dr1q)
## Tasks

- [x] https://github.com/votingworks/vxsuite/issues/1495
- [x] Create vx-iso install sticks for VxDev to ship to Ginny/Charlie
- [ ] Iterate on initial alpha & beta feedback and define minimum requirements for customer facing version

**Comment by mattroe** [comment]
Note to process everything tagged with VxDev as we determine next steps to wrap up this project

**Comment by mattroe** [comment]
@carolinemodic triaged and created a board to track VxDev feedback: https://github.com/orgs/votingworks/projects/23/views/45

I am comfortable calling the first version done after we complete the high priority issues on that list.
