### ISSUE TITLE
Improved State Management Architecture

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/vxsuite-roadmap#87]
# Context

- [Problem Brief](https://docs.google.com/document/d/1Ge-ZYh-8wtgsqEz48uldjHmb0sxZWetpXyzehiXNzrY/edit)
- [Solution Proposal](https://docs.google.com/document/d/1hBNyoyMIAzW6GDDM1efII5LezeBMWF8rF9cWf__G_nE/edit)
- [Solution Discussion Notes](https://docs.google.com/document/d/1NhYQu54bLirWXoQ4-cBGoJ3cP8wMpmcn0oyqtlA1_z4/edit#)

# Implementation Plan

## Phase 1 - Research/prototyping

Outline of research questions can be found in the solution proposal linked above. Some results from the prototyping can be found in this [implementation planning doc](https://docs.google.com/document/d/1Ja9mUw0IoNxkCKsJL9NKYRavZuRP0hGUmE4pTZs_Qp4/edit).

## Phase 2  - Converting the first app

- [ ] Separate VxScan app
- [ ] Convert VxScan backend to use Grout
- [ ] Use react-query to manage state in VxScan frontend
