### ISSUE TITLE
Software Updates in the Field v2

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite-roadmap#9]
## Team

Eng DRI: @umbernhard 
Product Definition and Security Advisor: @benadida 

**What is the feature or problem to solve?**
Completing the work to enable our machines to be updated from USB easily by a non-technical person.

**Why is it important?**
It is no longer desired/sustainable/practical with our system and customer volume to ship machines back and forth for updates between milestones.

## Supporting Documentation 

https://docs.google.com/document/d/1aYYNsknSWnqHvR2NLte2jAz79veIt4kuISrrcLZoCxM/edit#

## Timeline 
Have initial version of an install stick that works for installing VxDev by the end of May. Continously iterate on this and improve based on feedback from VxDev usage and requirements for integration with [Enhanced System Integrity v1](https://github.com/votingworks/vxsuite-roadmap/issues/3). July 1 deadline for vx-iso working to setup secure boot machines. 

## Tasks
With secure boot + dm-verity, we need to make exact disk image copies. Testing using `pv` has worked. Now we need a simple live-USB that can perform this install easily.

- [x] https://github.com/votingworks/vxsuite/issues/1762
- [x] https://github.com/votingworks/vx-iso/issues/23
- [x] https://github.com/votingworks/vx-iso/issues/24
- [x] https://github.com/votingworks/vx-iso/issues/25
- [x] https://github.com/votingworks/vx-iso/issues/26
- [ ] https://github.com/votingworks/vx-iso/issues/27
- [x] https://github.com/votingworks/vx-iso/issues/28
- [x] https://github.com/votingworks/vxsuite/issues/1828
- [x] https://github.com/votingworks/vx-iso/issues/39
- [x] https://github.com/votingworks/vxsuite/issues/1862

**Comment by carolinemodic** [comment]
Original scoping ticket: https://github.com/votingworks/vxsuite/issues/1502
